- name: Copy httpd-vhosts.conf ===> {{ apache_dir }}/conf/extra
  template:
    src: templates/httpd-vhosts.conf
    dest: "{{ apache_dir }}/conf/extra"
    owner: root
    group: root
    mode: '0644'

- name: Copy workers.properties ==> {{ apache_dir }}/conf
  template:
    src: templates/httpd-vhosts.conf
    dest: "{{ apache_dir }}/conf"
    owner: root
    group: root
    mode: '0644'
  # notify: restart apache
