- name: Copy apache service file
  template:
    src: templates/apache.service
    dest: "/etc/systemd/system/apache.service"
  when: ansible_service_mgr == "systemd"

- name: Copy httpd-vhosts.conf ===> {{ apache_dir }}/conf/extra
  template:
    src: templates/httpd-vhosts.conf
    dest: "{{ apache_dir }}/conf/extra/httpd-vhosts.conf"
    owner: root
    group: root
    mode: '0644'

- name: Copy workers.properties ==> {{ apache_dir }}/conf
  template:
    src: templates/workers.properties
    dest: "{{ apache_dir }}/conf/workers.properties"
    owner: root
    group: root
    mode: '0644'
  notify: restart apache
